EVENT_BUTTON_PRESSED = "EVENT_BUTTON_PRESSED"
EVENT_DOOR_COMPLETE_OPENED = "EVENT_DOOR_COMPLETE_OPENED"
EVENT_DOOR_COMPLETE_CLOSED = "EVENT_DOOR_COMPLETE_CLOSED"
EVENT_LIGHT_BARRIER_INTERRUPTED = "EVENT_LIGHT_BARRIER_INTERRUPTED"
EVENT_TIMEOUT = "EVENT_TIMEOUT"

EVENT = (EVENT_BUTTON_PRESSED,
         EVENT_DOOR_COMPLETE_CLOSED,
         EVENT_DOOR_COMPLETE_OPENED,
         EVENT_LIGHT_BARRIER_INTERRUPTED,
         EVENT_TIMEOUT)
